# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore
  displayName: 'dotnet restore' 
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build' 
- script: dotnet test PolymorphicPseudonymisation.Tests/PolymorphicPseudonymisation.Tests.csproj --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
  displayName: 'dotnet test'
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  displayName: 'publish test results'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: **/coverage.cobertura.xml
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)/PolymorphicPseudonymisation/bin/$(BuildConfiguration)/netstandard2.0/'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'



